# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Load .env file and set environment variables
      - name: Load .env file
        run: |
          while read -r line; do
            if [[ $line != \#* && $line == *"="* ]]; then
              name=$(echo $line | cut -d '=' -f 1)
              value=$(echo $line | cut -d '=' -f 2-)
              echo "$name=$value" >> $GITHUB_ENV
            fi
          done < .env

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Restart the PM2 process with the PORT from .env
      - run: pm2 restart shopdev-backend --update-env
        env:
          PORT: ${{ env.PORT }}